- README.md
> Fix typo Readme

- .github/HOW_TO_CONTRIBUTE.md
- scripts/release.js
docs update => spelling: github
Signed-off-by: Ayushman Singh Chauhan <ascb508@gmail.com>
> DOC: Fix spelling

- examples/dragonbone.html
- examples/index.html
- examples/loader.html
- examples/spine.html
- examples/sprite.html
Replace the Dragonbone animation, spine animation, and frame animation resource links in the examples to solve the two problems #7 #8.
> Fix resource blocked by CORS

- packages/plugin-renderer-dragonbone/lib/system.ts
> fix: Dragonbone Error #3

- README.md
- packages/eva.js/__tests__/game.spec.ts
- packages/eva.js/lib/core/System.ts
- packages/eva.js/lib/game/Game.ts
- packages/plugin-renderer-test/lib/index.ts
- packages/plugin-renderer-test/lib/system2.ts
> Fix system destroy

- .github/ISSUE_TEMPLATE.md
- packages/plugin-renderer/lib/System.ts
Bug fix
#30 
Add enableScroll property.
> fix: Renderer preventScroll bug #30

- examples/spriteAnimation.html
- packages/plugin-renderer-sprite-animation/lib/component.ts
- packages/plugin-renderer-sprite-animation/lib/system.ts
- packages/renderer-adapter/lib/SpriteAnimation.ts
- Add gotoAndPlay & gotoAndStop for AnimationSprite. #51
- Adding play times for SpriteAnimation #38
> feat: SpriteAnimation Feature

- packages/plugin-a11y/lib/A11ySystem.ts
> fix: Try catch checkA11yOpen #48

- packages/plugin-a11y/lib/A11ySystem.ts
- packages/plugin-renderer-sprite-animation/lib/component.ts
- packages/plugin-renderer-sprite-animation/lib/system.ts
- packages/plugin-renderer/lib/System.ts
- packages/plugin-renderer/lib/Transform.ts
> fix: Move pixi ticker to lateUpdate. #58

- packages/plugin-matterjs/lib/BodiesFactory.ts
- packages/plugin-matterjs/lib/Physics.ts
> Adding polygon body for Matterjs plugin

- examples/matterjs.html
- packages/plugin-matterjs/lib/BodiesFactory.ts
> fix: matterjs circle error

- .github/workflows/main.yml
> fix: action bug

- packages/eva.js/lib/core/GameObject.ts
- packages/eva.js/lib/loader/Resource.ts
- packages/plugin-renderer-dragonbone/lib/system.ts
- packages/plugin-renderer-graphics/lib/system.ts
- packages/plugin-renderer-img/lib/system.ts
- packages/plugin-renderer-lottie/lib/LottieSystem.ts
- packages/plugin-renderer-lottie/lib/utils.js
- packages/plugin-renderer-mask/lib/system.ts
- packages/plugin-renderer-nine-patch/lib/system.ts
- packages/plugin-renderer-spine/lib/SpineData.ts
- packages/plugin-renderer-sprite-animation/lib/system.ts
- packages/plugin-renderer-sprite/lib/system.ts
- packages/plugin-renderer-text/lib/system.ts
- packages/plugin-renderer-tiling-sprite/lib/system.ts
- packages/plugin-renderer/lib/Transform.ts
- packages/plugin-renderer/lib/manager/ContainerManager.ts
> fix: memory

- packages/plugin-renderer-dragonbone/lib/system.ts
- packages/plugin-renderer-graphics/lib/system.ts
- packages/plugin-renderer-img/lib/system.ts
- packages/plugin-renderer-mask/lib/system.ts
- packages/plugin-renderer-nine-patch/lib/system.ts
- packages/plugin-renderer-sprite-animation/lib/system.ts
- packages/plugin-renderer-sprite/lib/system.ts
- packages/plugin-renderer-text/lib/component.ts
- packages/plugin-renderer-text/lib/system.ts
- packages/plugin-renderer/lib/manager/ContainerManager.ts
> fix: destroy bug

- vite.config.ts
> fix: vite.config.ts alias

- packages/plugin-renderer-event/lib/component.ts
> fix: event type intelligence

- examples/src/spine38.ts
- packages/plugin-renderer-spine/lib/pixi-spine.js
- packages/plugin-renderer-spine38/lib/pixi-spine.js
> fix: spine change skin bug

- examples/src/matter.ts
- packages/plugin-matterjs/lib/PhysicsEngine.ts
> fix: bug when mouse.open=true

- packages/plugin-transition/lib/component.ts
> fix: transition play type definition

- examples/index.html
- examples/src/matter-change.ts
- examples/src/matter.ts
- packages/plugin-matterjs/lib/Physics.ts
- packages/plugin-matterjs/lib/PhysicsEngine.ts
- packages/plugin-matterjs/lib/PhysicsSystem.ts
> fix/fruit hit error when isTest=false

- packages/plugin-renderer-spine38/lib/pixi-spine.js
修复spine38播放带有mesh动作异常.
https://github.com/EsotericSoftware/spine-runtimes/pull/1881/commits/738f3f955084e443f408510972c2d0be1dad652b
no
> feat: 修复spine38播放带有mesh动作异常

- rollup.config.js
> fix: build

- packages/plugin-renderer-mask/lib/system.ts
> fix: mask destroy error

- packages/plugin-sound/lib/SoundSystem.ts
> fix: sound onResume no resume #119

- packages/plugin-renderer-spine38/api-extractor.json
- packages/plugin-renderer-spine38/index.js
> fix: spine38 d.ts

- examples/src/a11y.ts
- packages/plugin-a11y/lib/A11ySystem.ts
> fix: a11y hint change

- packages/plugin-transition/lib/component.ts
> fix: transition delay

- packages/plugin-matterjs/lib/PhysicsEngine.ts
- packages/plugin-transition/lib/component.ts
> fix: 解决延迟动画报错

- packages/plugin-sound/lib/SoundSystem.ts
> Fix: decodeAudioData promise rejection

- packages/plugin-renderer-spine38/lib/Spine.ts
- packages/plugin-renderer-spine38/lib/SpineSystem.ts
> fix: spine change error

- packages/plugin-sound/lib/SoundSystem.ts
> Catch the promise for ios 14.7 and above

- packages/eva.js/lib/core/ComponentObserver.ts
> fix: add remove component in one frame throw error

- examples/src/a11y.ts
- examples/src/sound.ts
- packages/plugin-a11y/lib/A11ySystem.ts
> fix: add zIndex params for A11ySystem & div insertBefore canvas

- packages/plugin-renderer-nine-patch/lib/system.ts
- packages/plugin-renderer-sprite/lib/system.ts
- packages/plugin-renderer-tiling-sprite/lib/system.ts
> fix: change error to console

- README.md
- README_CN.md
> fix: qrcode

- packages/eva.js/lib/loader/Resource.ts
> fix: resource can't loaded

- packages/eva.js/lib/core/GameObject.ts
- packages/eva.js/lib/core/observer.ts
- packages/plugin-renderer-img/lib/system.ts
- packages/plugin-renderer/lib/manager/ContainerManager.ts
- packages/spine-base/lib/SpineSystem.ts
> fix: protect

- packages/plugin-renderer/lib/compressedTexture/fix/BaseTextureMixin.ts
- packages/plugin-renderer/lib/compressedTexture/fix/TextureMixin.ts
> fix: remove symbol

- packages/eva.js/lib/core/GameObject.ts
> fix: throw error addComponent to a destroyed gameObject

- package.json
- packages/eva.js/package.json
- packages/miniprogram-adapter/package.json
- packages/miniprogram-pixi/package.json
- packages/plugin-a11y/package.json
- packages/plugin-evax/package.json
- packages/plugin-matterjs/package.json
- packages/plugin-renderer-dragonbone/package.json
- packages/plugin-renderer-event/package.json
- packages/plugin-renderer-graphics/package.json
- packages/plugin-renderer-img/package.json
- packages/plugin-renderer-lottie/package.json
- packages/plugin-renderer-mask/package.json
- packages/plugin-renderer-nine-patch/package.json
- packages/plugin-renderer-render/package.json
- packages/plugin-renderer-spine/package.json
- packages/plugin-renderer-spine38/package.json
- packages/plugin-renderer-spine40/package.json
- packages/plugin-renderer-sprite-animation/package.json
- packages/plugin-renderer-sprite/package.json
- packages/plugin-renderer-test/package.json
- packages/plugin-renderer-text/package.json
- packages/plugin-renderer-tiling-sprite/package.json
- packages/plugin-renderer/package.json
- packages/plugin-sound/package.json
- packages/plugin-stats/package.json
- packages/plugin-transition/package.json
- packages/renderer-adapter/package.json
- packages/spine-base/package.json
- rollup.config.js
> fix: IIFE min file not have window variable.

- packages/miniprogram-pixi/lib/index.ts
> fix: export settings/UPDATE_PRIORITY from miniprogram-pixi

- packages/plugin-renderer/lib/System.ts
> fix(core): fix typo for enableScroll of RendererSystemParams

- packages/plugin-stats/lib/hooks/GLHook.ts
- packages/plugin-stats/lib/hooks/TextureHook.ts
> fix: In multi scene，white screen while use stats plugin #204
